// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuJ0wSB976RXAKxorM-v5tU63ZtTsAtq4',
    appId: '1:864969606154:web:e2919082eeaa7ff9ae8bf3',
    messagingSenderId: '864969606154',
    projectId: 'vanxuan-5198f',
    authDomain: 'vanxuan-5198f.firebaseapp.com',
    databaseURL: 'https://vanxuan-5198f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vanxuan-5198f.appspot.com',
    measurementId: 'G-0CM50TF2EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADM3O5dnLPbi5sAEnI4Ius6O2Uf_p392g',
    appId: '1:864969606154:android:664055fe7b90798bae8bf3',
    messagingSenderId: '864969606154',
    projectId: 'vanxuan-5198f',
    databaseURL: 'https://vanxuan-5198f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vanxuan-5198f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGdSGNG0RBv9WJuZXSREB8BeJPsImMXOc',
    appId: '1:864969606154:ios:5b6f1bc1e69f3aacae8bf3',
    messagingSenderId: '864969606154',
    projectId: 'vanxuan-5198f',
    databaseURL: 'https://vanxuan-5198f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vanxuan-5198f.appspot.com',
    iosClientId: '864969606154-ujp6fpf99lv8grukh5bt6ah04smr27t1.apps.googleusercontent.com',
    iosBundleId: 'com.example.vanxuan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGdSGNG0RBv9WJuZXSREB8BeJPsImMXOc',
    appId: '1:864969606154:ios:5b6f1bc1e69f3aacae8bf3',
    messagingSenderId: '864969606154',
    projectId: 'vanxuan-5198f',
    databaseURL: 'https://vanxuan-5198f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vanxuan-5198f.appspot.com',
    iosClientId: '864969606154-ujp6fpf99lv8grukh5bt6ah04smr27t1.apps.googleusercontent.com',
    iosBundleId: 'com.example.vanxuan',
  );
}
